In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("C:\\Users\\Chandrika\\Desktop\\RBA - Fraud and Risk Analytics\\bank cleaned coded data.csv")
data.head()

age  job  marital  education  default  balance  housing  loan  duration  \
0   58    6        1          3        0     2143        1     0       261   
1   44   11        2          2        0       29        1     0       151   
2   33    3        1          2        0        2        1     1        76   
3   47    2        1          4        0     1506        1     0        92   
4   33    4        2          4        0        1        0     0       198   

   pdays  previous  y  
0     -1         0  0  
1     -1         0  0  
2     -1         0  0  
3     -1         0  0  
4     -1         0  0

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [4]:
array = data.values

# Features: first 20 columns
X = array[:,0:-1]

# Target variable: 'response_binary'
Y = array[:,-1]

In [5]:
X

array([[  58,    6,    1, ...,  261,   -1,    0],
       [  44,   11,    2, ...,  151,   -1,    0],
       [  33,    3,    1, ...,   76,   -1,    0],
       ...,
       [  72,    7,    1, ..., 1127,  184,    3],
       [  57,    2,    1, ...,  508,   -1,    0],
       [  37,    3,    1, ...,  361,  188,   11]], dtype=int64)

In [6]:
Y

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [7]:
# 20% of the data will be used for testing
test_size= 0.20
seed = 7
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=test_size, random_state=seed)

In [8]:
# with statsmodels
import statsmodels.api as sm
# adding a constant
 
model = sm.Logit(Y_train, X_train).fit()
predictions = model.predict(X_train) 
 
print_model = model.summary()
print(print_model)

Optimization terminated successfully.
         Current function value: 0.295416
         Iterations 7
                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                36168
Model:                          Logit   Df Residuals:                    36157
Method:                           MLE   Df Model:                           10
Date:                Sat, 05 Sep 2020   Pseudo R-squ.:                  0.1866
Time:                        13:08:49   Log-Likelihood:                -10685.
converged:                       True   LL-Null:                       -13137.
Covariance Type:            nonrobust   LLR p-value:                     0.000
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.0408      0.001    -34.885      0.000      -0.043      -0.039
x2            -0.0193      0.

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report

#Build the model
clf = LogisticRegression()

# Train the classifier
clf.fit(X_train, Y_train)

#test the model
y_pred = clf.predict(X_test)

#classification report
cr = (classification_report(Y_test, y_pred))

C:\Users\Chandrika\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
confm = confusion_matrix(Y_test, y_pred)
pre = precision_score(Y_test, y_pred)
recall = recall_score(Y_test, y_pred)
f1_score = f1_score(Y_test, y_pred)

print(confm)
print(pre)
print(recall)
print(f1_score)

[[7884  143]
 [ 830  186]]
0.5653495440729484
0.1830708661417323
0.2765799256505576


In [12]:
Y_test.shape

(9043,)

In [15]:
buy = data[data['y'] == 1]
DTBuy = data[data['y'] == 0]
n = len(buy)/float(len(DTBuy))
print(n)
print('Buy TD: {}'.format(len(data[data['y'] == 1])))
print('Dont Buy TD: {}'.format(len(data[data['y'] == 0])),"\n")

0.1324833425179099
Buy TD: 5289
Dont Buy TD: 39922 

